exodjango/my_car_site/cars/urls.py
from django.urls import path
from . import views

app_name = 'cars'

urlpatterns = [
    path('add/', views.add_view , name='add'),
    path('list/', views.list_view, name='list'),
    path('delete/', views.delete_view, name='delete')
]

exodjango/my_car_site/my_car_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cars/', include('cars.urls'))
]

exodjango/my_car_site/cars/models.py
from django.db import models

# Create your models here.
class Car(models.Model):
    # pk autoincrement
    brand = models.CharField(max_length=301)
    year = models.IntegerField()

    def __str__(self) -> str:
        return f"Car is {self.brand} {self.year}"   

exodjango/my_car_site/cars/views.py
from ast import Delete
from audioop import reverse
from django.shortcuts import render, redirect
from django.urls import reverse

from . import models

# Create your views here.
def list_view(request):
    all_cars = models.Car.objects.all()
    context = {"cars_list" : all_cars}
    return render(request, 'cars/list.html', context=context)

def add_view(request):
    if request.POST :
        brand = request.POST['brand']
        year = int(request.POST['year'])
        models.Car.objects.create(brand=brand, year=year)
        return redirect(reverse('cars:list'))
    else :
        return render(request, 'cars/add.html')

def delete_view(request):
    if request.POST :
        pk = request.POST['pk']
        try :
            models.Car.objects.get(pk=pk).delete()
            return redirect(reverse('cars:list'))
        except:
            print('pk not found')
            return redirect(reverse('cars:list'))
        
    else :
        return render(request, 'cars/delete.html')

exodjango/my_car_site/cars/templates/cars/add.html
{% extends 'base.html' %}

{% block content %}

<div class='container'>
    <h1>add.html</h1>
    <h2>Add a new car to databse</h2>
    <form action="" method='POST'>
        {% csrf_token %}
        <div class='form-group'>
            <label for="brand">Brand</label>
            <input class='form-control' type="text" id='brand' name='brand'>
        </div>
        <div class='form-group'>
            <label for="year">Year</label>
            <input class='form-control' type="text" id='year' name='year'>
        </div>
        <input class = 'btn btn-primary' type="submit">
    </form>
</div>


{% endblock content %}

exodjango/my_car_site/cars/templates/cars/delete.html
{% extends 'base.html' %}

{% block content %}
<div class='container'>
    <h1>delete.html</h1>
    <form action="" method='POST'>
        {% csrf_token %}
        <div class='form-group'>
            <label for="pk">PK Number :</label>
            <input class='form-control' type="text" id='pk' name='pk'>
        </div>
        <input class='btn btn-primary' type="submit">

    </form>
</div>


{% endblock content %}

exodjango/my_car_site/cars/templates/cars/list.html
{% extends 'base.html' %}

{% block content %}
<div class='container' > 
    <h1>test.html</h1>
    <ul>
        {% for cars in  cars_list%}
        <li>{{cars}}</li>
        {% endfor %}
    </ul>

</div>

{% endblock content %}

exodjango/my_car_site/templates/base.html
 <html lang="en">
 <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    
    <title>Document</title>
 </head>
 <body>

    {% comment %} NAVBAR {% endcomment %}
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-link" href="{% url 'cars:list' %}">LIST</a>
              <a class="nav-link" href="{% url 'cars:add' %}">ADD</a>
              <a class="nav-link" href="{% url 'cars:delete' %}">DELETE</a>
            </div>
          </div>
        </div>
      </nav>

    {% block content %}
    
    {% endblock content %}



 </body>
 </html>